name: Magento 2 Module CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # You can change this to the required PHP version for your project

      # Install Composer
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      # Install Magento 2 dependencies
      - name: Install dependencies with Composer
        run: |
          composer install

      # Install Magento 2 (if necessary)
      - name: Install Magento 2
        run: |
          php bin/magento setup:install \
            --base-url=http://localhost \
            --db-host=localhost \
            --db-name=magento2 \
            --db-user=root \
            --db-password=root \
            --admin-firstname=Admin \
            --admin-lastname=User \
            --admin-email=admin@example.com \
            --admin-user=admin \
            --admin-password=admin123

      # Run tests (Replace this with your own test command)
      - name: Run Magento 2 unit tests
        run: |
          php bin/magento dev:tests:run

  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Lint PHP code (using PHPStan, PHPMD, or another linter)
      - name: Run PHPStan
        run: |
          composer require --dev phpstan/phpstan
          ./vendor/bin/phpstan analyse src --level=7
